lib/kino/vega_lite.ex, notebooks/examples.livemd, test/kino/vega_lite_test.exs
Ticks 1. in https://github.com/elixir-nx/livebook/issues/340.
https://user-images.githubusercontent.com/17034772/121569609-437e1500-ca21-11eb-9be5-1da6e714dd49.mp4
=> Add support for periodical callbacks in the VegaLite widget

lib/kino/vega_lite.ex, test/kino/vega_lite_test.exs
=> Terminate widget as soon as its parent terminates

README.md
=> Change how license is rendered in README.md

lib/kino/vega_lite.ex, test/kino/vega_lite_test.exs
Reverts elixir-nx/kino#7
We need the widget in order to push data.
=> Revert "Return the Vl widget on periodically"

lib/kino/vega_lite.ex, test/kino/vega_lite_test.exs
=> Validate VegaLite data points and automatically convert to map

lib/kino/ets.ex, lib/kino/output.ex, test/kino/ets_test.exs
Also see https://github.com/elixir-nx/livebook/pull/358.
=> Enable the refetch feature for ETS tables

lib/kino/ets.ex, test/kino/ets_test.exs
=> Handle ETS tables with mixed number of columns

lib/kino/ets.ex, test/kino/ets_test.exs
See https://github.com/elixir-nx/kino/pull/22#discussion_r655409898 thread.
=> Disable sorting for ETS tables

lib/kino/data_table.ex, lib/kino/ets.ex, lib/kino/render.ex, test/kino/data_table_test.exs, test/kino/ets_test.exs
Closes #17.
https://user-images.githubusercontent.com/17034772/122764304-a41e1500-d29f-11eb-8cc3-541b941c1ffa.mp4
=> Implement DataTable

lib/kino.ex, lib/kino/config.ex, lib/kino/output.ex, test/kino/output_test.exs
See https://github.com/elixir-nx/livebook/issues/392#issuecomment-867590608.
=> Make inspect options globally configurable

lib/kino.ex, lib/kino/markdown.ex, lib/kino/output.ex, lib/kino/render.ex
Follow up to https://github.com/elixir-nx/livebook/pull/404.
cc @wojtekmach :cat2:
=> Add markdown output and meta-struct

lib/kino/data_table.ex, test/kino/data_table_test.exs
=> Support structs in DataTable

lib/kino.ex, lib/kino/vega_lite.ex, test/kino/ecto_test.exs
=> Change Kino.render/1 to return hidden value

lib/kino/control.ex, lib/kino/input.ex
=> Add missing guards to Kino.Input and Kino.Control

CHANGELOG.md, README.md, lib/kino.ex, mix.exs
Once we are ready on Livebook side.
=> Release 0.4.0

lib/kino/js/live.ex, lib/kino/js/live/context.ex, test/kino/js/live/context_test.exs, test/kino/js/live_test.exs
=> Move live context functions to the Context module

lib/kino/data_table.ex, lib/kino/ets.ex, lib/kino/vega_lite.ex
=> Remove deprecated start widget functions

lib/kino/control.ex, lib/kino/input.ex, lib/kino/js.ex, lib/kino/js/live.ex, lib/kino/output.ex, test/kino/js_data_store_test.exs
=> Unify output refs

lib/kino/control.ex, lib/kino/input.ex, lib/kino/subscription_manager.ex, test/kino/control_test.exs, test/kino/subscription_manager_test.exs
https://user-images.githubusercontent.com/17034772/149792089-d69a02b4-c413-46f5-9604-3f7a28075a9f.mp4
=> Add stream API for control events

lib/kino/control.ex, lib/kino/data_table.ex, lib/kino/ecto.ex, lib/kino/ets.ex, lib/kino/frame.ex, lib/kino/image.ex, lib/kino/input.ex, lib/kino/js.ex, lib/kino/js/live.ex, lib/kino/markdown.ex, lib/kino/subscription_manager.ex, lib/kino/table.ex, test/kino/control_test.exs, test/kino/input_test.exs, test/kino/subscription_manager_test.exs
https://user-images.githubusercontent.com/17034772/149975139-cc5dbdba-33eb-4dc6-874f-8f56962d7631.mp4
=> Add combined stream for multiple controls

lib/kino/js.ex
See https://github.com/livebook-dev/nerves_livebook/issues/156#issuecomment-1020699164.
=> Resolve assets archive path based on priv path at runtime

lib/kino/js.ex
=> Add security note in Kino.JS docs

lib/kino/js/live.ex
Follow up to https://github.com/livebook-dev/livebook/pull/982.
=> Document binary payloads

lib/kino/data_table.ex, lib/kino/ecto.ex, lib/kino/utils/table.ex, test/kino/data_table_test.exs, test/kino/ecto_test.exs
=> Simplify column computation and add types to Ecto results

lib/kino/smart_cell.ex, lib/kino/smart_cell/db_connection.ex, lib/kino/smart_cell/server.ex
See https://github.com/livebook-dev/livebook/pull/1041.
=> Add callbacks for scanning evaluation context

lib/kino/smart_cell.ex, lib/kino/smart_cell/server.ex
See https://github.com/livebook-dev/livebook/pull/1048.
=> Add smart cell callback for scanning the evaluation result

lib/kino/js/live.ex, lib/kino/js/live/server.ex, lib/kino/smart_cell.ex, lib/kino/smart_cell/server.ex
See https://github.com/livebook-dev/livebook/pull/1050.
=> Add support for smart cell editor

lib/kino/application.ex, lib/kino/counter.ex, lib/kino/smart_cell.ex, lib/kino/smart_cell/db_connection.ex, lib/kino/smart_cell/sql.ex, test/kino/counter_test.exs, test/kino/smart_cell/db_connection_test.exs
https://user-images.githubusercontent.com/17034772/159354243-ca904a8c-d549-4e84-980d-b60b55ff86c8.mp4
=> Generate unique default names for smart cell variables

lib/assets/db_connection/main.css, lib/assets/sql/main.css
=> Select inputs for Safari

lib/assets/chart_builder/main.js, lib/kino/smart_cell/chart_builder.ex, test/kino/smart_cell/chart_builder_test.exs
https://user-images.githubusercontent.com/5660941/160162466-feab35aa-0fd4-453d-a587-211c8312e9c0.mov
=> Initial support for aggregate

lib/assets/chart_builder/main.css, lib/assets/chart_builder/main.js, lib/kino/smart_cell/chart_builder.ex, test/kino/smart_cell/chart_builder_test.exs
New four column layout and chart title option
=> New layout and chart title

lib/assets/chart_builder/main.css, lib/assets/chart_builder/main.js, lib/kino/smart_cell/chart_builder.ex, test/kino/smart_cell/chart_builder_test.exs
Moves count aggregation to the field options
=> Count as special option

lib/assets/chart_builder/main.js
=> Fix: removes count from data variable

lib/assets/chart_builder/main.css, lib/assets/chart_builder/main.js, lib/kino/smart_cell/chart_builder.ex
The only small change in behavior is that I’m no longer resetting the type fields at each channel field change. This turned out to be a not so good user experience. I feel we have a more consistent behavior between all fields now.
=> Refactor to Vue

lib/assets/chart_builder/main.css
=> Chart builder - responsiveness

lib/kino/smart_cell/chart_builder.ex, test/kino/smart_cell/chart_builder_test.exs
This PR strictly solves the persistence issue, assuming that we will always have a single layer plot for a while.
=> Adds layers for chart builder attrs

lib/assets/chart_builder/main.css, lib/assets/chart_builder/main.js
=> New design

lib/assets/chart_builder/main.css
=> Primary blue color

lib/assets/db_connection/main.css, lib/assets/db_connection/main.js, lib/assets/sql/main.css, lib/assets/sql/main.js
=> Smart cells - new design

lib/assets/vega_lite/main.css, lib/assets/vega_lite/main.js
=> VegaLite - LiveBook inspired theme

lib/assets/chart_builder/main.css, lib/assets/chart_builder/main.js, lib/assets/db_connection/main.css, lib/assets/db_connection/main.js, lib/assets/sql/main.css, lib/assets/sql/main.js
=> Smart Cells - responsiveness

lib/assets/db_connection/main.css, lib/assets/db_connection/main.js, lib/assets/sql/main.css, lib/assets/sql/main.js, lib/kino/smart_cell/db_connection.ex, lib/kino/smart_cell/sql.ex, test/kino/smart_cell/sql_test.exs
Closes #142.
https://user-images.githubusercontent.com/17034772/165619169-cf7a717e-1574-4b7f-9e96-905f7bf56202.mp4
=> Add timeout setting to SQL cell

lib/kino/js.ex, lib/kino/js/live/server.ex, lib/kino/output.ex, lib/kino/smart_cell.ex, test/kino/js/live_test.exs
See https://github.com/livebook-dev/livebook/pull/1164.
=> Handle ping messages in JS.Live

lib/kino/data_table.ex, mix.lock, test/kino/data_table_test.exs
=> Improve edge cases in Kino.DataTable

CHANGELOG.md, README.md, mix.exs
=> Release 0.6.2

lib/kino/layout.ex, lib/kino/output.ex, lib/kino/render.ex, mix.exs
Closes #164, closes #157.
[kino_layout.webm](https://user-images.githubusercontent.com/17034772/182672612-c3ffd028-6f15-43c5-9612-59171e359520.webm)
=> Add layout utilities

lib/kino/control.ex, lib/kino/js/live/context.ex, lib/kino/js/live/server.ex, lib/kino/test.ex, test/kino/control_test.exs, test/kino/data_table_test.exs, test/kino/js/data_store_test.exs
Follow up to https://github.com/livebook-dev/livebook/pull/1333.
=> Use binary origin

README.md
Updating the docs to include `kino_benchee` for https://github.com/livebook-dev/kino/issues/132
=> Adding kino_benchee to readme

lib/kino.ex, lib/kino/bridge.ex, lib/kino/terminator.ex
=> Ensure processes get terminated before reevaluation

lib/kino/input.ex, lib/kino/output.ex
See https://github.com/livebook-dev/livebook/pull/1538.
=> Add image input

lib/assets/tree/main.css, lib/assets/tree/main.js, lib/kino.ex, lib/kino/tree.ex, test/kino/tree_test.exs
=> Add Kino.Tree kino

lib/kino/table.ex
=> Fix: table pagination

README.md
=> Adding missing kinos to readme

lib/kino/bridge.ex, lib/kino/debug.ex, lib/kino/test/group_leader.ex, test/kino/debug_test.exs
=> Fall back to default dbg when the call is outside Livebook context

lib/kino/input.ex, lib/kino/output.ex
See https://github.com/livebook-dev/livebook/pull/1610.
=> Add audio input

lib/kino/input.ex, lib/kino/output.ex, test/kino/input_test.exs
Closes #136.
See https://github.com/livebook-dev/livebook/pull/1622.
=> Add file input

CHANGELOG.md, README.md, mix.exs
=> Release v0.8.1

lib/kino/bridge.ex, lib/kino/frame.ex, lib/kino/test.ex, lib/kino/test/group_leader.ex, test/kino/frame_test.exs
Closes #149.
https://user-images.githubusercontent.com/17034772/215151812-78e3417c-d3df-43c6-a7a3-81c329d93568.mov
=> Add support for sending frame updates to a specific client

lib/kino.ex, lib/kino/html.ex
=> Add Kino.HTML

lib/kino/data_table.ex, lib/kino/ets.ex, lib/kino/table.ex, mix.exs
=> Make the table behaviour public

lib/kino.ex, test/kino_test.exs
=> Do not terminate async_listen processes when stream finishes

CHANGELOG.md, README.md, mix.exs
=> Release v0.9.0

lib/assets/html/main.js, lib/assets/mermaid/main.js, lib/kino/html.ex, lib/kino/js.ex, lib/kino/mermaid.ex, lib/kino/output.ex
See https://github.com/livebook-dev/livebook/pull/1958.
=> Add CDN information to Kino.JS assets

.github/workflows/test.yaml, lib/kino/download.ex, lib/kino/process.ex, lib/kino/tree.ex, test/kino/data_table_test.exs
=> Fix map key ordering on OTP 26

lib/kino/frame.ex, lib/kino/output.ex, lib/kino/render.ex
=> Add option to disable frame placeholder

CHANGELOG.md, README.md, mix.exs
=> Release v0.10.0

lib/kino.ex, lib/kino/input.ex, lib/kino/smart_cell.ex
Spent some time reading through the Kino docs this morning and came across a few things I thought could be improved. 🙂 
Will close #301.
=> Docs: Various additions/fixes

lib/kino.ex
=> Return pid when calling Kino.listen

lib/kino.ex, lib/kino/control.ex, lib/kino/data_table.ex, lib/kino/input.ex, lib/kino/shorts.ex, lib/kino/text.ex, mix.exs, test/kino/shorts_test.exs
=> Add kino shorts

lib/kino/render.ex, lib/kino/text.ex, test/kino/text_test.exs
=> Support ANSI escape sequences in `Kino.Text`

lib/kino/input.ex, test/kino/input_test.exs
=> Fix date validation when allowed range is given

lib/kino/table.ex
=> Reset pagination on sorting

lib/kino/data_table.ex, test/kino/data_table_test.exs
Closes https://github.com/livebook-dev/kino_db/issues/56.
=> Inspect non-utf8 binaries in Kino.DataTable

lib/kino/remote_execution_cell.ex, lib/kino/rpc.ex, test/kino/remote_execution_cell_test.exs, test/kino/rpc_test.exs
=> Fix code with interpolation in remote execution smart cell

lib/kino/application.ex, lib/kino/debug.ex, test/kino/debug_test.exs
Fixes https://github.com/elixir-lang/elixir/issues/12687#issuecomment-1820525658.
=> Don't discard currently registered dbg_callback

lib/kino/table.ex
Only today did I realize that I wasn't following the spec correctly.
I've fixed both sides and we can release simultaneously if you think it's worth it
=> Fix table download to match the spec

lib/kino/bridge.ex, lib/kino/hub.ex
See https://github.com/livebook-dev/livebook/pull/2540.
=> Add function for getting client's user info

lib/kino/data_table.ex, lib/kino/table.ex, test/kino/data_table_test.exs
closes #382 
https://github.com/livebook-dev/kino/assets/5660941/a15fc863-5aae-49f2-a92c-72bec67b9222
=> DataTable update

lib/kino.ex, lib/kino/bridge.ex
For https://github.com/phoenixframework/flame/pull/40.
=> Add Kino.beam_paths/0
