mix.exs

I think examples is a great starting point but given it's common to start with a README, there is the license information, and we have the convenient "Next" button to go to examples, I thought I'd open it up. But yeah, happy to leave things as is, just curious :)

Change docs main page to README

---

lib/kino/vega_lite.ex
test/kino/vega_lite_test.exs

This way, in Livebook, instead of
widget =
Vl.new(...)
|> ...
|> Kino.VegaLite.start()
|> Kino.render()
Kino.VegaLite.periodically(widget, ...)
we can do
Vl.new(...)
|> ...
|> Kino.VegaLite.start()
|> Kino.VegaLite.periodically(...)
Should we do the same for push/clear/etc?

Return the Vl widget on periodically

---

lib/kino/ets.ex
lib/kino/output.ex
lib/kino/render.ex
lib/kino/vega_lite.ex
test/kino/ets_test.exs

This defines a new output type - an interactive data table. The client (Livebook) makes queries to the widget process to get rows (with optional support for pagination and sorting). For the output rendering see https://github.com/elixir-nx/livebook/pull/356.
Further, this defines `Kino.ETS` widget that adheres to the dynamic table communication protocol and makes for an interface for browsing an ETS table.
https://user-images.githubusercontent.com/17034772/122280192-3e213e80-cee9-11eb-8458-ab8caa5968d5.mp4
FTR: I think the widget shouldn't support deletion or any other kind of mutation and should be just a presentation layer. This way we force the user to document any relevant mutations as code in Elixir cells, which is in the spirit of reproducability.

Add dynamic table output and ETS table widget

---

lib/kino.ex
lib/kino/image.ex
lib/kino/output.ex
lib/kino/render.ex
test/kino/image_test.exs

Defines a new output type - raw image, and also introduces a simple `%Kino.Image{}` struct that implements the `Kino.Render` protocol and is thus automatically rendered as an image.
https://user-images.githubusercontent.com/17034772/122954271-950e9400-d37f-11eb-9e8e-e3cc13a94d73.mp4

Add image output and meta-struct

---

lib/kino.ex
lib/kino/data_table.ex
lib/kino/ets.ex
lib/kino/render.ex
lib/kino/vega_lite.ex
test/kino/data_table_test.exs
test/kino/ets_test.exs
test/kino/vega_lite_test.exs

Renaming all `Kino.SomeDynamicWidget.start(...)` to `Kino.SomeDynamicWidget.new(...)` to make it transparent whether the widget is a stateful process or a static struct.

Start dynamic widgets with new for consistency

---

test/kino/ecto_test.exs

Fixes tests failing as of https://github.com/livebook-dev/kino/issues/35#issuecomment-886224030.
@josevalim initially I omitted these mock resolutions as they weren't relevant for the tests, but I didn't realise it relies on the suite being terminated early, which it does.

Resolve all mock calls in Ecto tests

---

lib/kino.ex
lib/kino/frame.ex
lib/kino/output.ex
lib/kino/render.ex
lib/kino/vega_lite.ex
test/kino/frame_test.exs
test/kino/vega_lite_test.exs

Closes #48. For the Livebook counterpart see https://github.com/livebook-dev/livebook/pull/688.
This introduces a new dynamic output that wraps a single static output, which can be replaced at any time. Additionally, we now have `Kino.animate` wrapping the most common use case.
https://user-images.githubusercontent.com/17034772/140779100-c21ebb5e-422e-41cd-acb0-42566bcd6da1.mp4
*Sidenote: `Kino.animate` is how to flip book in Livebook*

Add Kino.Frame for animations

---

lib/kino.ex
lib/kino/bridge.ex
lib/kino/input.ex
lib/kino/output.ex
lib/kino/render.ex
test/kino/input_test.exs

See https://github.com/livebook-dev/livebook/pull/714.
Currently `Kino.Input.read` raises in the terminal, but we can easily improve it to read and parse input. This can be handled separately though.

Introduce Kino.Input

---

lib/kino.ex
lib/kino/frame.ex
lib/kino/output.ex
lib/kino/vega_lite.ex
test/kino_test.exs

Closes #59.
@josevalim actually not sure if `Kino.inspect/2` makes sense with this change, because `Kino.render/1` covers most cases and if someone really wants to inspect Kino structs they can always use `IO.inspect` for that?

Return the rendered term from Kino.render/1

---

lib/kino/control.ex
lib/kino/input.ex
lib/kino/output.ex
test/kino/control_test.exs

Adds support for form control. The form is composed of regular inputs, but inside form those inputs are not synchronized across users. Similarly, refreshing the page discards input values. As with other controls, there is no API for reading the value, instead we can subscribe to events, in this case submit or change. This enables each user to send inputs data a user-specific an event.
https://user-images.githubusercontent.com/17034772/145636268-e681bf03-cec6-4d89-bca8-221b19d86b6d.mp4
*For the Livebook part see https://github.com/livebook-dev/livebook/pull/790.*

Add Kino.Control.form/2

---

lib/kino/js.ex
lib/kino/js/live.ex
lib/kino/output.ex
lib/kino/render.ex
lib/kino/vega_lite.ex
test/kino/js_test.exs

This adds configuration options to enable exporting `Kino.JS` widgets into Live Markdown. Similar to what we already did for Vega-Lite, just generalized.

Add support for exporting JS output

---

lib/assets/data_table/main.css
lib/assets/data_table/main.js
lib/kino/data_table.ex
lib/kino/ecto.ex
lib/kino/ets.ex
lib/kino/output.ex
lib/kino/render.ex
lib/kino/table.ex
lib/kino/utils/table.ex
test/kino/data_table_test.exs
test/kino/ecto_test.exs
test/kino/ets_test.exs

This changes the underlying implementation of `Kino.DataTable`, `Kino.ETS` and `Kino.Ecto` to JavaScript widgets, instead of the specific `:data_table` output we currently have. This removes another bit from the Kino-Livebook contract, which also means we can more easily change the tables behaviour in the future.
The public API doesn't change. The only difference is that the table state is now synchronized across uses, which we intended to do anyway.
https://user-images.githubusercontent.com/17034772/147990052-fb3c21f3-60f5-46d6-bbd0-b9a52e826540.mp4
I introduced a `Kino.Table` abstraction that builds on top of `Kino.JS.Live`, but I'd keep it private for now.

Implement tables with Kino.JS.Live

---

lib/kino/application.ex
lib/kino/js.ex
lib/kino/js/live.ex
lib/kino/js/live_server.ex
lib/kino/js_data_store.ex
lib/kino/output.ex
lib/kino/render.ex
test/kino/data_table_test.exs
test/kino/ecto_test.exs
test/kino/ets_test.exs
test/kino/js/live_test.exs
test/kino/js_data_store_test.exs
test/kino/vega_lite_test.exs

Adds a reference to JS widgets and the widget messages. This way we can do multiplexing with a single subscription process in https://github.com/livebook-dev/livebook/pull/843.

Add reference to JavaScript outputs and messages

---

lib/kino/bridge.ex
lib/kino/js/live/context.ex
lib/kino/js/live_server.ex
lib/kino/js_data_store.ex
test/kino/data_table_test.exs
test/kino/ecto_test.exs
test/kino/ets_test.exs
test/kino/js/live_test.exs
test/kino/vega_lite_test.exs
test/support/livebook_case.ex
test/support/test/group_leader.ex
test/support/test/js_live.ex

Adds `Kino.Bridge.broadcast(topic, message)` that goes through the group leader and is later broadcasted to interested processes on Livebook side. This way we can send events from JS server to Livebook as a single message and use the pubsub there, as opposed to sending the event to individual processes in Livebook.
Also adds `Kino.Bridge.send(pid, message)`, so that all communication goes through the bridge API.

Introduce broadcast communication

---

lib/kino/input.ex
test/kino/input_test.exs

Add type validations for default input value

---

lib/kino/js/live.ex
lib/kino/js/live/context.ex
lib/kino/table.ex
lib/kino/vega_lite.ex
test/support/test_modules/live_counter.ex

We are now sending the event directly, so there's no reason to return `ctx` from `broadcast_event`, as this gives false idea that it changes the context.

Update broadcast_event to return :ok

---

CHANGELOG.md
lib/assets/vega_lite/main.js
lib/kino/js.ex

Options other than export are not particularly useful and they don't work inside iframe, so we should hide them.

Hide Vega-Lite actions not compatible with iframe

---

lib/assets/data_table/main.css
lib/assets/data_table/main.js
lib/kino/table.ex

I want to rebase #42, it should be much simpler with the abstractions we now have. This PR extracts some generic changes, specifically we now show the total number of entries and also support optional type information on columns (this we don't currently use, but it's a simple addition and useful moving forward).
*Note that the types above are just a showcase, we don't show these for `DataTable`.*

Show more table metadata

---

lib/assets/data_table/main.css
lib/assets/data_table/main.js

I made the navigation bar also use monospaced font for consistency, and so that we don't need to load another font just for that.

Use monospace font in tables

---

lib/kino/js.ex

First PR! feedback appreciated :)
Inspired by https://github.com/livebook-dev/kino/issues/96
After struggling to understand how to apply CSS to custom widgets, I've added an example that imports a `main.css` file and a random font from google fonts.
Hopefully, this should give people a better idea of how to apply CSS to their own widgets.

Add example for styling a Kino HTML widget

---

lib/kino/data_table.ex
test/kino/data_table_test.exs

First non-documentation PR! Let me know if I can adjust anything :) 
This PR allows `DataTable` to accept a `:name` option.
I would find this feature very useful if there's an interest in accepting it. Open to any feedback or suggested changes.

Custom table names

---

lib/kino/data_table.ex
lib/kino/utils/table.ex
test/kino/data_table_test.exs

We support keyword lists in cases where we need to preserve the order, however we want to allow any key type, as we do with maps.

Add support for string keys in DataTable

---

lib/kino/smart_cell.ex
lib/kino/smart_cell/server.ex
test/support/test/smart_cell.ex

Adds an option for the smart cell to reevaluate when the generated source changes. Related to #106.

Add an option to reevaluate smart cell on change

---

lib/kino/js/data_store.ex
test/kino/js/data_store_test.exs

Follow up to https://github.com/livebook-dev/livebook/pull/1067. For "static" JS outputs we have a shared `JS.DataStore` server that replies to all connection requests. When data for the given output gets garbage collected, we would currently still reply with `nil`. To match the behaviour of regular server processes, we should ignore the request, as if the server terminated.

Ignore connections to JS data store when there is no matching data

---

lib/assets/chart_builder/main.js
lib/kino/smart_cell/chart_builder.ex

I restarted the runtime and then evaluated everything using `Ctrl+Shift+Enter`. In such case, by the time the smart cell loads, everything is evaluated, so it receives the available data in the initial payload, so we don't want to disable the fields.

Keep initial chart builder fields enabled when the data is already available

---

lib/kino/control.ex
test/kino/control_test.exs

We currently have `Kino.Control.stream(source)` for control events, however this API is blocking. This adds
* `Kino.Control.stream(source, fn event -> ... end)`
* `Kino.Control.stream(source, state, fn event, state -> ... end)`
both of which are non-blocking. The same goes for `Kino.Control.tagged_stream/1`.

Add callback API for control events

---

CHANGELOG.md
README.md
mix.exs

FTR we are going to retire 0.6.0, because it is not compatible with upcoming Livebook v0.6. Specifically, smart cells evaluation now relies on pings, so without #147 it would block.

Release 0.6.1

---

lib/kino/data_table.ex
test/kino/data_table_test.exs

Closes #150.
Sidenote: `Table.to_rows_with_info/2` always returns all columns in `info`, but I think info is more about the table itself, rather than the specific rows. @josevalim wdyt?

Adjust DataTable to respect the :keys order

---

lib/assets/data_table/main.js
lib/kino/data_table.ex
lib/kino/table.ex
mix.exs
mix.lock

Uses `Enumerable.slice` on row data if available, otherwise takes and caches enumerable items on demand.
This relies on some small changes to `Table`, I'm opening this for easier discussion.

Make data traversal lazy in Kino.DataTable

---

lib/kino/process.ex
mix.exs

This PR addresses half of #154. It supports rendering supervision trees top-down and left to right. You can render the supervisor by name or by PID. The links that are displayed are only between processes within the supervision tree and process links external to the supervision tree are omitted.
I haven't added tests yet, but will add them once I know I am on the right track :smile:. Thanks in advance for the review!
Some sample images for reference:

Adding supervision tree visualizer

---

lib/kino/process.ex
lib/kino/process/tracer.ex

This PR implements #159 
Continuing the discussion from that issue:
> Should we not show the bars if the process already exists or should we show the bar from beginning to end?
At the moment I have the bar starting when a process is spawned and stopped when it exits (both of which have to be present during the trace in order for the bar to appear). In other words, it doesn't look like Mermaid renders anything unless there is both an actor activate and deactivate. That and it doesn't look like we can start bars at arbitrary points on the sequence. Rather it looks like they have to start and stop on events. All this to say, *I think* if we want to keep the bars, they'll only be present when a process starts and stops during the trace.
> Regarding the messages, can we do any sort of mouse …

Adding process tracing

---

lib/kino/test.ex

This PR adds documentation about how to get a reference to a Kino's source in `assert_smart_cell_update` without having to perform an exact match on the entire source.
There is a little bit of context in [this PR](https://github.com/livebook-dev/kino/pull/172) I had opened, but it turned out that functionality was already possible but not obvious to me 😛, and not documented.

Update docs for assert_smart_cell_update

---

lib/kino/process.ex

When using `Kino.Process.app_tree` when some process was registered under a name like `:"some process"`, I got a Mermaid error like this:
```
Mermaid
Parse error on line 4:
...ne):::root ---> 1(:"some process...
-----------------------^
Expecting 'SEMI', 'NEWLINE', 'SPACE', 'EOF', 'GRAPH', 'DIR', 'subgraph', 'SQS', 'SQE', 'end', 'AMP', 'DOUBLECIRCLEEND', 'PE', '-)', 'STADIUMEND', 'SUBROUTINEEND', 'ALPHA', 'COLON', 'PIPE', 'CYLINDEREND', 'DIAMOND_STOP', 'TAGEND', 'TRAPEND', 'INVTRAPEND', 'START_LINK', 'LINK', 'STYLE', 'LINKSTYLE', 'CLASSDEF', 'CLASS', 'CLICK', 'DOWN', 'UP', 'DEFAULT', 'NUM', 'COMMA', 'MINUS', 'BRKT', 'DOT', 'PCT', 'TAGSTART', 'PUNCTUATION', 'UNICODE_TEXT', 'PLUS', 'EQUALS', 'MULT', 'UNDERSCORE', got 'STR'
```
Figured out that's because of the colon at the beginning of the …

Fix Mermaid error when inspected process name starts with colon

---

lib/kino/terminator.ex

A task started with `Kino.start_child` may be finished when the cell reevalutes, so `DynamicSupervisor.terminate_child` may be unsuccessful and that's fine.

Don't crash when terminating finished tasks

---

lib/kino/bridge.ex
lib/kino/js/live.ex
lib/kino/js/live/context.ex
lib/kino/js/live/server.ex
lib/kino/test.ex
test/kino/js/live_test.exs
test/support/test_modules/live_counter.ex

Closes #171.
[send_event.webm](https://user-images.githubusercontent.com/17034772/182946178-99d2b0ba-01b6-47db-ae92-eab9aa4fb2c7.webm)
Note that if the same JS view is rendered multiple times, all instances are still the same client, because client.

Add send_event/4 for Kino.JS.Live

---

lib/assets/download/main.css
lib/assets/download/main.js
lib/kino/download.ex
mix.exs
test/kino/download_test.exs

Attempts to address https://github.com/livebook-dev/kino/issues/19.
I am new to Kino, and not a Javascript exeprt, so I would appreciate some feedback on this.
The Javascript code was mostly taken from [this jsfiddle](https://jsfiddle.net/wtp5a0o8/1/).
I tested it in my local livebook instance like this:

Add Kino.Download

---

lib/kino/inspect.ex
lib/kino/raw.ex
lib/kino/render.ex
lib/kino/utils.ex
mix.exs

Closes #182.
[tabbed_atom_pid.webm](https://user-images.githubusercontent.com/17034772/183126271-26166836-39a3-4f27-9b2e-98692f47bb65.webm)

Add default tabbed output for pids and atoms

---

lib/kino.ex
lib/kino/control.ex
test/kino/control_test.exs
test/kino_test.exs

Closes #168, closes #177.
[`Kino.listen/2,3`](https://youtu.be/RmGe-LY5HQs?t=8) replaces `Kino.Control.stream/2,3` and is more general because it accepts any stream. Similarly `Kino.animate/2` is added and `Kino.animate/3` is extended to handle streams.

Add Kino.listen and expand Kino.animate

---

lib/kino/process.ex
test/kino/process_test.exs

This PR fixes `Kino.Process` supervisor/app tree visualization when the tree includes processes that did not start (their `start` function returned `:ignore`). In the process, I ended up refactoring `traverse_processes/3` a bit.
Happy to answer any questions!
[Livebook demonstration](https://gist.github.com/zachallaun/aa2ce2a24660cb23341dfeeb23c51964)
Previous:
After PR:

Fix `Kino.Process` visualization for non-started processes

---

lib/kino.ex
lib/kino/image.ex
lib/kino/js.ex
lib/kino/js/live.ex
lib/kino/markdown.ex
lib/kino/mermaid.ex
lib/kino/process.ex
mix.exs
test/kino/process_test.exs

Mermaid can be useful to render dynamic representation of data structures. Currently we use `Kino.Markdown` in those cases, however markdown outputs are never persisted in the notebook source, so there's no option to render them in the docs. This adds a dedicated `Kino.Mermaid`, which can be persisted as mermaid snippet and therefor rendered in the docs.

Add Kino.Mermaid

---

lib/kino/image.ex

Especially that `StbImage` epects `:jpg`, it is confusing to figure out where it should be `:jpeg` and where `:jpg`.

Support both :jpeg and :jpg as shorthand MIME types

---

lib/kino/smart_cell.ex
lib/kino/smart_cell/server.ex

Allows `c:Kino.SmartCell.to_source/1` to return a list, then when converting to a Code cell, each chunk becomes its own cell.

Add support for multi-chunk smart cell source

---

lib/kino/input.ex
lib/kino/output.ex

Allow `Kino.Input.textarea` inputs to be given a new option, `monospace`.
When `monospace` is set to `true`, this allows Livebook to render the textarea with a monospaced font.
This is to support https://github.com/livebook-dev/livebook/pull/1565
When combined with the pull request above it results in:

Add `monospace` option to `Kino.Input.textarea`

---

mix.exs

Move Kino.Tree under the "Kinos" section in docs

---

lib/kino/data_table.ex
test/kino/data_table_test.exs

My SQL query smartcell crashed with the `List.to_string/1` `ArgumentError` exception when returning an `array_agg` list of timestamps from a postgres query.
This rescues the exception and applies the `value_to_string/1` to each list item before running the whole list through `inspect`.
The test checks for the standard charlist behaviour along with some non-standard values.

Support non-charlist List values in DataTable

---

lib/kino.ex
test/kino_test.exs

It's important for apps that a failure in event callback is isolated and doesn't crash the stream.

Ignore failures in listen and animate

---

lib/kino/render.ex
lib/kino/utils.ex

This is my first time contributing to this project, and I'm excited to make my first pull request. Please let me know if there's anything I can improve!
Closes #43.
Detects image type by its magic number and renders the image as a tabbed output.

Add automatic image detection

---

lib/kino.ex
test/kino_test.exs

Adds a version of `listen/2` that processes all events concurrently in separate processes.

Add concurrent listen

---

lib/kino/js/live.ex
lib/kino/js/live/server.ex
test/kino/js/live_test.exs
test/support/test_modules/live_counter.ex

Fix the wrong `JS.Live.handle_call/3` behavior, described in #273.

Support deferred reply in `Kino.JS.Live.handle_call/3`

---

lib/kino.ex

Without this, it took me a while to debug that a Broadway pipeline that I had started with `Kino.start_child/1` was being restarted after `Broadway.stop/1`. This was of course happening because I didn't set `restart: :transient`, but I think having `terminate_child/1` makes sense if we provide `start_child/1`.

Add Kino.terminate_child/1

---

lib/kino/frame.ex
lib/kino/test/group_leader.ex
test/kino/frame_test.exs

Currently if a kino is crated inside `Kino.async_listen`, it is garbage collected as soon as the async process terminates, because the frame doesn't reference it on time.
```elixir
button = Kino.Control.button("Click")
frame = Kino.Frame.new()
Kino.async_listen(button, fn _event ->
Kino.Frame.render(frame, Kino.HTML.new("Content"))
end)
Kino.Layout.grid([button, frame])
```
This makes frame render/append synchronous to make sure we send the reference request before the async process terminates.

Fix premature cleanup of kinos pushed to frame asynchronously

---

lib/kino.ex

When interval ms is given to `Kino.animate` the `Kino.Frame.periodically` is being used with the `Kino.Frame.render` inside, which never returns because periodically blocks it.
This PR changes to use `listen` instead of `periodically`
Closes #280

Using listen instead of periodically

---

lib/kino/frame.ex
test/kino/frame_test.exs

Initially we wanted to avoid additional process, but this eventually lead to issues (#280) and having this separate API in addition to `Kino.listen` and `Kino.animate` can be confusing.

Deprecate Kino.Frame.periodically/4

---

lib/kino/bridge.ex
lib/kino/hub.ex

Adds function to access information about the running app, in particular, when running with Teams hub it shows the user that started the session, useful for auditing purposes.

Add Kino.Hub.app_info/0

---

lib/kino/control.ex
lib/kino/output.ex
test/kino/control_test.exs

Main PR and discussion in Livebook: livebook-dev/livebook#2145

Add options to `Kino.Control.keyboard`

---

lib/kino/process.ex

Support remote processes in Kino.Process

---

lib/kino/js.ex
lib/kino/js/data_store.ex
lib/kino/js/live.ex
lib/kino/js/live/server.ex
lib/kino/mermaid.ex
lib/kino/table.ex
test/kino/js/data_store_test.exs
test/kino/js/live_test.exs
test/kino/js_test.exs
test/support/test_modules/live_counter.ex

Also improves the export API for `Kino.JS`.

Allow Kino.JS.Live outputs to be exported

---

lib/kino.ex

Add Kino.start_child!/1

---

lib/kino/input.ex
test/kino/input_test.exs

The min, max and default options are all converted to a `NaiveDateTime`, so we cannot compare them using `DateTime`.
Fixes #335.

Fix Kino.Input.utc_datetime opts validation

---

lib/kino/input.ex

Hi there!
@jonatanklosko was faster than I in addressing #325 with #326 -- thanks for the quick fix!
Since I had some changes laying around already, I decided to post them here for feedback/discussion, I wouldn't mind if they are eventually not accepted.
<details>
~~I noticed `Kino.Input.date` was lacking tests, and was happy to see @jonatanklosko added one yesterday!~~
~~I had a plan to cover more of the possible cases, and so tried some form of table-testing to reduce verbosity. I wonder how others see this type of test code in Elixir, given it also adds some cognitive complexity (`unquote`, `Macro.escape`, ...).~~
~~The constraints in this case are simple enough that property-based testing would also be a fun exercise :-)~~
</details>
Update: removed tests to keep the PR more focused. …

Kino.Input error messages

---

lib/kino.ex
lib/kino/bridge.ex

Add Kino.tmp_dir/0

---

.github/workflows/test.yaml

Fixes warning in recent workflow runs:
> The following actions uses node12 which is deprecated and will be forced
> to run on node16: actions/checkout@v2, actions/cache@v2.
>
> For more info:
> https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
Example run: https://github.com/livebook-dev/kino/actions/runs/6142008298

Bump versions in GitHub test workflow

---

lib/kino/data_table.ex

Enable livemd export for Kino.DataTable

---

lib/kino/input.ex

adds debounce option pretty much the same way as `phx-debounce` from LiveView works, except of a different default value.
This change is accompanied by a change in Livebook, see https://github.com/livebook-dev/livebook/pull/2224 for details

Add debounce option for inputs

---

lib/kino/input.ex
test/kino/input_test.exs

`phx-debounce="blur"` is the problem

Fix input range on Safari

---

CHANGELOG.md
README.md
mix.exs

Release v0.11.0

---

assets/remote_execution_cell/main.js
lib/assets/remote_execution_cell/build/main.js
lib/kino/js/live/context.ex
lib/kino/remote_execution_cell.ex
lib/kino/smart_cell.ex
lib/kino/smart_cell/server.ex

Currently we set intellisense node through the client as `ctx.setSmartCellEditorIntellisenseNode(node, cookie)`, but if there are multiple clients we run this for each of them, which doesn't really make sense. I added a new option to the smart cell init configuration, so we can do `{:ok, ctx, [editor: [..., intellisense_node: ...]]}`, which sets the initial value. Then, it can be updated with a new API `reconfigure_smart_cell(ctx, editor: [intellisense_node: ...])`.
I also added an option to programmatically set the smart cell source with `reconfigure_smart_cell(ctx, editor: [source: ...])`.

Add API for setting smart cell editor source and intellisense node

---

lib/kino/remote_execution_cell.ex
lib/kino/smart_cell.ex
lib/kino/smart_cell/server.ex

This is a breaking change, but I think it's better to do it sooner than later. Currently the user specifies under which `attr` the editor source should be placed and it is only available inside the `to_source(attrs)` callback. This PR makes the flow more explicit, we expose a new callback `handle_editor_change(source, ctx)` and it is up to the user to keep it in assigns and put in `attrs`. This could be used to update the UI based on the editor source (for example to parse the code and show errors).
Note that this is a breaking change only in that the smart cell implementation needs to be updated (a simple change). It doesn't change anything on Livebook side, and smart cell serialization is also not affected (provided the same attribute is used).

Make the smart cell editor source explicitly managed

---

lib/kino/js.ex

When bundling into `my_cell/build`, we specify build as the assets path, which works most of the time. But we may also want to have static files alongside, such as `my_cell/logo.png`. With the new option we can do `use Kino.JS, assets_path: "lib/assets/my_cell", entrypoint: "build/main.js"`.

Add a Kino.JS option to specify custom entrypoint file

---

lib/kino/frame.ex
lib/kino/layout.ex
lib/kino/render.ex
test/kino/frame_test.exs
test/kino/layout_test.exs
test/kino/tree_test.exs

For frames `Kino.Output.to_livebook/2` returns an output with the current set of outputs. Currently containers (grid/tabs/frame) convert their contents to output eagerly, and so if the content representation changes, a future container render is not going to know about it. Example:
```elixir
frame_inner = Kino.Frame.new()
grid = Kino.Layout.grid([frame_inner])
Kino.Frame.render(frame_inner, "content")
grid
```
This PR makes the conversion lazy, so that containers store their contents as is, and only call `Kino.Output.to_livebook/2` on render.

Convert container contents to output lazily

---

assets/tree/src/App.js
lib/kino/tree.ex
test/kino/tree_test.exs

Closes #387.
Auto-expand tuples of up to 6 elements in `Kino.Tree` by default.
I've introduced the following changes:
- Add `"kind"` (e.g. `"tuple"`, `"list"`, etc.) attribute to tree's data,
- Use the `"kind"` attribute to change the logic for auto-expanding data; this now makes it easy to apply the same logic to lists and maps (if desired),
- Flatten the structure of the tree data: introduce `"expanded_before"` and `"expanded_after"` attributes,
- Refactor the UI code: rename `expanded` and `setExpanded` to `isExpanded` and `setIsExpanded` to better fit JavaScript conventions,
- Refactor the backend code: introduce `leaf_node` and `branch_node` to ensure that we build consistent data (without introducing more structs/types).

`Kino.Tree`: auto-expand tuples of up to 6 elements

---

lib/kino.ex

Add Kino.recompile/0

---

lib/kino/markdown.ex
lib/kino/text.ex

A user asked in the Slack channel about how to use the chunk option. I noticed there were no examples in the docs. So I copied the examples [from the original PR adding that option](https://github.com/livebook-dev/livebook/pull/2174) to the docs.

Add doc examples about the chunk option of Kino.Text.new/2 and Kino.Markdown.new/2

---

lib/kino/bridge.ex

Closes #406.
An internal API for monitoring session clients. Also see https://github.com/livebook-dev/livebook/pull/2530.

Add internal client monitoring

---

lib/kino/process.ex

This topic addresses #408
I added an extra argument to `seq_trace` and `render_seq_trace`, that accepts an extra argument to augment the labeling logic.
I have not tested the code yet, nor did I see any tests in the repo.
I hope it works.
I am now going to test this in a project I'm working on, and might add an extra commit that augments the example, showing off what the custom label can do.
I've also exposed `label_from_value` as I think it may add some value to people's custom's logic's
```elixir
@spec foo(term()) :: label_response()
defp foo(message) do
case message do
{:"$gen_call", _ref, {:special, _, msg}} -> "CALL: #{label_from_value(msg)}"
{:"$gen_cast", _ref, {:special, _, msg}} -> "CAST: #{label_from_value(msg)}"
_ -> :continue
end
end
```
is one such logic I used in mocking up …

Custom Label Logic

---

mix.exs

I think this group header is a little more self-evident and is also consistent with the [Kino module doc](https://hexdocs.pm/kino/Kino.html#module-built-in-kinos).

Rename "Kino implementations" to "Built-in Kinos"

---

lib/kino/table.ex

Fix for https://github.com/livebook-dev/kino_explorer/issues/165

Fix: sample data for empty data

---

lib/kino/process.ex
test/kino/process_test.exs

This PR addresses https://github.com/livebook-dev/kino/issues/430
By default, ETS table rendering is disabled and the rendering looks as it already does:
If you enable ETS table rendering you see the following:
At the moment this PR is lacking tests and could use a little refactoring, but I want to make sure the diagrams are right before writing the tests and performing last mile clean up.

Render ets tables

---

lib/kino/hub.ex
lib/kino/workspace.ex

We no longer use the word "hub" in user-facing contexts.

Move Kino.Hub to Kino.Workspace

---

lib/kino/process.ex

The color of a worker was hard to distinguish from the color of a supervisor for some people (myself, for example).
Maybe it's hard for me to distinguish between them because I have a low level of color blindness.
I came up with the new color value by asking ChatGPT for a color that would be colorblind-friendly, given we would maintain the color of a supervisor in the graph.

New color for process on supervision tree rendering

---

lib/kino/bridge.ex
lib/kino/proxy.ex

An example would be:
```elixir
defmodule AppRouter do
use Plug.Router
plug :match
plug :dispatch
get "/hello" do
send_resp(conn, 200, "world")
end
match _ do
send_resp(conn, 404, "oops")
end
end
Kino.Proxy.listen(AppRouter)
```

Accept module plugs in Kino.Proxy.listen/1

---

lib/kino/process.ex
test/kino/process_test.exs

Hi there!
TLDR; I added labels to the process nodes to make it more clear what the processes represent.
I was using `Kino.Process` in Livebook to try and figure out how some elements of the Membrane RTC Engine work. I won't go into the details, but suffice to say this is a foreign code base to me, and it wasn't clear from the get go:
* What the supervision tree looks like.
* How it the internal genservers relate to each other.
* How that ties into my phoenix app.
So I was poking around blindly until I got my RTC Engine's process's graphed with Kino. This is what it looked like for reference:
Cool! So now I get to see the process layout, but I'm still blind as to what all this actually is. I still don't know what Membrane is doing. To get a bit more insight, changed the label for the PID …

Show worker/supervisor ids in app supervision graph

---

lib/kino/bridge.ex
lib/kino/input.ex

Raise an error when trying to read input value from a background process

---

lib/kino.ex
lib/kino/js/live.ex

Update docs on nested Kino.start_child/1

---

lib/kino/debug/pipeline.ex
test/kino/debug_test.exs
test/support/test_modules/user_as_table.ex

Currently a pipeline with Explorer operations and `|> dbg()` hangs and times out. The pipeline `c:Kino.JS.Live.init/1` calls `Kino.Frame.render/2`, which may result in `Kino.start_child/1` underneath. In the past `Kino.Frame.render/2` used `GenServer.cast`, so the `init` callback would not block, finish and unlock the other `Kino.start_child/1`. However, we changed `Kino.Frame.render/2` to use `GenServer.call` (https://github.com/livebook-dev/kino/commit/aae7a1b0a22f1b5273a5d058c5831b916513438d), so now `init` blocks, but the nested `Kino.start_child/1` hangs, until `init` times out.
To fix it, I moved `Kino.Frame.render/2` from `init` to a subsequent `handle_info`.

Fix dbg pipeline when result renders as Kino.JS.Live

---

lib/kino/process.ex

Don't show :undefined id when rendering supervision trees

---

lib/assets/audio/main.js
lib/kino/audio.ex
test/kino/audio_test.exs

Addresses https://github.com/livebook-dev/kino/issues/457 
Adds support for `play` and `pause` functions for `Kino.Audio`.
I have tested it with:
```elixir
req =
Req.get!(
"https://file-examples.com/storage/fe9f6f893066954d9aac3a2/2017/11/file_example_MP3_5MG.mp3"
)
kino = Kino.Audio.new(req.body, :mp3)
```
```elixir
for n <- 0..11 do
case rem(n, 2) do
0 -> Kino.Audio.play(kino)
1 -> Kino.Audio.pause(kino)
end
:timer.sleep(1000)
end
```

Add play and pause to audio

---

lib/kino.ex
lib/kino/audio.ex
lib/kino/bridge.ex
lib/kino/image.ex
lib/kino/input.ex
lib/kino/render.ex
lib/kino/shorts.ex
lib/kino/video.ex
test/kino/attribute_store_test.exs
test/kino/process_test.exs
test/kino/video_test.exs

Fix various typos and improve language

---

lib/kino/layout.ex
lib/kino/render.ex

This PR allows the behaviour of the grid to be controlled using [grid-template-columns](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns)
Example usage
Requires Livebook PR [#2718](https://github.com/livebook-dev/livebook/pull/2718)

Support specifying column ratios in `Kino.Layout.grid`

---

lib/kino/remote_execution_cell.ex
test/kino/remote_execution_cell_test.exs

Closes #464.
We could use a different delimiter, but we would checks to find one that is not present in the string, so I think it's better to just use the triple delimiter.

Use triple quote when remote cell content contains a quote

---

lib/kino/frame.ex
lib/kino/process/tracer.ex
lib/kino/terminator.ex

We run into cases where `Frame.append` from a connected node times out. There is no reason for these calls to have a timeout, so I think we are fine with `:infinity`.

Increase timeouts for frame render and append

---

lib/kino/js/live/context.ex
lib/kino/smart_cell.ex
lib/kino/smart_cell/server.ex

https://github.com/user-attachments/assets/a2661ee7-1797-4e6b-94f0-6111aac07e0c
<details><summary>Source</summary>
```elixir
defmodule SmartCellWithEditorToggle do
use Kino.JS
use Kino.JS.Live
use Kino.SmartCell, name: "Smart cell with editor toggle"
@impl true
def init(attrs, ctx) do
source = attrs["source"] || ""
ctx = assign(ctx, source: source, visible: false)
{:ok, ctx, editor: [source: source, visible: false]}
end
@impl true
def handle_connect(ctx) do
{:ok, %{}, ctx}
end
@impl true
def handle_event("toggle_editor", %{}, ctx) do
visible = not ctx.assigns.visible
{:noreply,
ctx
|> assign(visible: visible)
|> reconfigure_smart_cell(editor: [visible: visible])}
end
@impl true
def handle_editor_change(source, ctx) do
{:ok, assign(ctx, source: source)}
end
@impl true
def to_attrs(ctx) do …
```

Support toggling smart cell editor visibility

---

lib/kino/test.ex

Just a little helper. I [needed it](https://github.com/livebook-dev/kino_flame/pull/3/files#diff-c52cefe4b6d3ef3ce5b7cb63552730c3a4b39030a7ed75ccd2e6985eba5ab4b5R180) and thought others might benefit from this, too.

Add `Kino.Test.push_smart_cell_editor_source/2` to test editor changes

---

lib/kino/terminator.ex

Example
```elixir
defmodule Slow do
use GenServer
def start_link(time) do
GenServer.start_link(__MODULE__, time, name: __MODULE__)
end
def init(time) do
Process.sleep(time)
{:ok, time}
end
end
Kino.start_child({Slow, 10_000})
```
When we "Evaluate" and "Stop" (which terminates the evaluator), the child still ends up starting. Consequently, if we try to evaluate again (which starts a new evaluator), we get `:already_started`, because the process is still under the kino supervision tree.

Call off start_child when the group leader terminates

---

lib/kino/proxy.ex

Added example from https://news.livebook.dev/
`Livebook 0.13: expose an HTTP API from your notebook`

Update proxy.ex with more examples

---

lib/kino/layout.ex
lib/kino/proxy.ex
lib/kino/render.ex

It could be useful for frames where a lot of results are appended. However, instead of making it specific to frames, I think we can add it to grid, which is pretty much the API for a generic container. So to get a scrollable frame we do:

Add :max_height option for Kino.Layout.grid/2

---

lib/kino/control.ex
test/kino/control_test.exs

Supersedes #484.
Pretty sure we went with keyword list, because it's convenient to write, but there was no reason to actually restrict the tags to atoms.

Allow any term to be used as tag in Kino.Control.tagged_stream/1

---

lib/kino/render.ex

Otherwise folks may copy and paste the contents
of this file, accidentally using Kino.Output's private
API. Relying on Kino.Render.Any is ok because that's
a public fallback.
Other options to consider: use Kino.Text |> Kino.Render.to_livebook,
although that's more verbose.

Use Kino.Render.Any.to_livebook/1

---

lib/kino/js/live.ex
lib/kino/mermaid.ex
lib/kino/render.ex
lib/kino/test.ex
test/kino/mermaid_test.exs

It would be nice to have a test for this. Maybe a `Kino.JS.export(Kino.JS.t())` function that would allow us to get the exported value?

Fix mermaid output export

---

lib/kino/control.ex
lib/kino/screen.ex
test/kino/control_test.exs
test/kino/screen_test.exs

I choose to keep `control/2` for now because using `handle_event/3` requires us to wrap everything in `{:noreply, ...}` tuples. But if you prefer `handle_event`, let me know @hugobarauna / @jonatanklosko.
I also have to figure out how to control that a certain page should only be seen by a certain user (the `client_id`).
---
If someone wants to give it a try without depending on Kino main, here is a notebook:
`````
```elixir
Mix.install [:kino]
```
```elixir
defmodule Kino.Screen do
@moduledoc ~S"""
Provides a LiveView like experience for building forms in Livebook.
Each screen must implement the `c:init/1` and `c:render/1` callbacks.
Event handlers can be attached by calling the `control/2` function.
Note the screen state is shared across all users seeing the given page.
Let's see some …

Add Kino.Screen

---

lib/kino/js.ex

add back and simply ignore :export_key for now. #494

Ignore :export_key passed to Kino.JS.new/3 instead of raising

---

lib/kino/control.ex
test/kino/control_test.exs

This will be useful, for example, for using custom kino in "custom form", like this one: https://gist.github.com/hugobarauna/0150a90009f737e6949c9285f34329de
So users  could build something like this:
Here's the code for this example: https://gist.github.com/hugobarauna/a8adeb29d67ee7dda54da8f75a82274f

Add Kino.JS.Live events support to subscribe/unsubscribe
